# Generated by Django 4.1.3 on 2022-11-11 09:24

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeState',
            fields=[
                ('uuid', core.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'State',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('uuid', core.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('value', models.IntegerField(default=100, verbose_name='Value')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challengestate', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Challenge',
            },
        ),
    ]
