COMPETITION_COMING = 'coming'
COMPETITION_ARCHIVE = 'archive'
COMPETITION_LIVE = 'live'

COMPETITION_STATUS_CHOICES = (
    (COMPETITION_COMING, 'coming'),
    (COMPETITION_ARCHIVE, 'archive'),
    (COMPETITION_LIVE, 'live')
)

ENROLLMENT_SOLO = 'solo'
ENROLLMENT_TEAM = 'team'

ENROLLMENT_CHOICES = (
    (ENROLLMENT_SOLO, 'solo'),
    (ENROLLMENT_TEAM, 'team')
)

# MN
ENROLLMENT_SOLO_MN = 'хувь хүн'
ENROLLMENT_TEAM_MN = 'баг'
