gin:
  mode: "debug"

postgres:
  url: "postgresql://butterfly_user:butterfly_password@localhost:5432/butterfly_db"
  log: false

auth:
  private_key_path: "./privateKey.pem"
  public_key_path: "./publicKey.pem"
  timeout: 600
