# Generated by Django 3.1.7 on 2021-04-26 08:43

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('uuid', apps.core.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('name', models.CharField(default='OyuSec', max_length=100, verbose_name='Name')),
                ('description', models.TextField(default='CTF', verbose_name='Description')),
                ('status', models.CharField(choices=[('coming', 'coming'), ('archive', 'archive'), ('live', 'live')], default='coming', max_length=100, verbose_name='Status')),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.URLField(blank=True, default='https://github.com/OyuTech/Utils/blob/main/oyusec/oyusec.png', null=True)),
                ('rule', models.TextField(default='')),
                ('prize', models.TextField()),
                ('location', models.CharField(default='онлайн', max_length=100, verbose_name='Location')),
                ('enrollment', models.CharField(choices=[('solo', 'solo'), ('team', 'team')], default='solo', max_length=100, verbose_name='Enrollment')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('weight', models.FloatField(default=20.0, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Competition',
            },
        ),
        migrations.CreateModel(
            name='CompetitionUser',
            fields=[
                ('uuid', apps.core.models.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('score', models.PositiveIntegerField(default=0.0, verbose_name='Score')),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('place', models.PositiveIntegerField(default=0, verbose_name='Place')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
            ],
            options={
                'verbose_name': 'Competition User',
            },
        ),
    ]
